package com.pingidentity.spring.example.controllers;

import com.pingidentity.spring.example.config.NonceProvider;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.security.oauth2.client.OAuth2AuthorizedClient;
import org.springframework.security.oauth2.client.OAuth2AuthorizedClientService;
import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken;
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.security.oauth2.core.OAuth2Error;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.client.RestTemplate;

@Controller
public class HomeController {

  @Autowired
  private OAuth2AuthorizedClientService authorizedClientService;
  @Autowired
  private RestTemplate restTemplate;
  @Autowired
  private NonceProvider nonceProvider;

  @GetMapping("/")
  public String home(OAuth2AuthenticationToken authentication, Model model) {

    // Verify nonce value if there is a token id
    if (authentication.getPrincipal() instanceof OidcUser &&
        !nonceProvider.verify((OidcUser) authentication.getPrincipal())) {
      OAuth2Error oauth2Error = new OAuth2Error(
          "invalid_nonce",
          "Token nonce differs from the nonce, generated by this application.",
          null
      );
      authentication.setAuthenticated(false);
      throw new OAuth2AuthenticationException(oauth2Error, oauth2Error.toString());
    }
    model.addAttribute("details", authentication.getPrincipal().getAttributes());

    // Get the client for the authorized user
    OAuth2AuthorizedClient client = authorizedClientService
        .loadAuthorizedClient(
            authentication.getAuthorizedClientRegistrationId(),
            authentication.getName());

    // The endpoint for getting user info
    if (client != null) {
      String userInfoEndpointUri = client.getClientRegistration()
          .getProviderDetails().getUserInfoEndpoint().getUri();
      // Make a request to get the user info
      if (!StringUtils.isEmpty(userInfoEndpointUri)) {
        ResponseEntity<Map> response = restTemplate.exchange(userInfoEndpointUri, HttpMethod.GET, null, Map.class);
        model.addAttribute("userInfo", response.getBody());
      }
    }

    return "oauthLogin";
  }

  @GetMapping("favicon.ico")
  @ResponseBody
  public void returnNoFavicon() {
  }
}
